version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./captcha_attempts:/app/captcha_attempts
    env_file:
      - .env
    environment:
      - SELENIUM_CHROME_HEADLESS=true
      - SELENIUM_CHROME_SANDBOX=false
      - CHROME_DRIVER_PATH=/usr/bin/chromedriver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
